---
title: 异常
date: 2020-10-19 17:33:12
tags:
	- Java
	- 基础知识
categories:
	- Java
cover:
	https://gitee.com/jasonM4A1/pictureHost/raw/master/20201019173631.jpg
---

# 异常

## 概述

异常，指的是程序在执行过程中，出现的非正常的情况，最终导致`JVM`的非正常停止。

在`Java`等面向对象的编程语言中，异常本身是一个类，产生异常就是创建异常对象并抛出一个异常对象。`Java`处理异常的方式是中断处理。

> 异常指的并不是语法错误，如果语法错了，在编译阶段就不会通过。

## 异常体系

异常机制其实是帮助我们找到程序中的问题。异常的根类是`java.lang.Throwable`，其下有两个子类：

1. `java.lang.Error`，严重错误`Error`，是无法处理的错误。只能事先避免，好比绝症。
2. `java.lang.Exception`，表示异常，异常产生后程序员可以通过代码的方式纠正，是程序继续运行。也就是我们平时所说的异常。

![](https://gitee.com/jasonM4A1/pictureHost/raw/master/20201019173824.png)

## 异常分类

异常可以根据处于不同时期分为：

+ **编译时期异常**：checked异常。在编译时期，就会检查。如果没有处理异常，则编译失败。对于编译时异常，Java要求我们强制处理这个异常，要么`try...catch`，要么`throws`。

+ **运行时期异常**：runtime异常。在运行时期，检查异常。在编译时期，运行异常是不会被编译器检查报错的。如数学异常。

  对于运行时异常，我们就可以不去处理。

## 异常方法

+ `void printStackTrace()`：在控制台打印异常的详细信息。包含了异常的类型，异常的原因，还包含异常出现的位置。在开发和调试阶段，都得使用`printStackTrace`。
+ `String getMessage()`：获取发生异常的原因。提示给用户的时候，就提示错误原因。
+ `String toString()`：获取异常的类型和异常描述信息，在日常开发中几乎不使用。

## 异常处理

在处理Java异常中我们常常会遇到这四个关键字：`try...catch`、`finally`、`throw`、`throws`。

下面我们逐个讲解这五个关键字。

### throw——抛出异常

+ 作用：`throw`用在方法内，用来抛出一个异常对象，将这个异常对象传递到调用者处，并结束当前方法的执行。

+ 格式：

  ~~~java
  //throw new 异常类名(参数)
  throw new NullPointerException("要访问的arr数组不存在");
  throw new ArrayIndexOutOfBoundException("该索引在数组中不存在，已超出范围");
  ~~~

**代码演示**

~~~java
public class Test {
    //定义一个 根据索引找到数组中元素 的方法
    public static int getElement(int[] arr, int index) {
        //如果索引越界,就执行throw语句
        if (index < 0 || index > arr.length-1) {
			//这是一个运行时异常，我们可以不用去处理
            throw new ArrayIndexOutOfBoundsException("大哥！索引越界了啊！");
        }
        return arr[index];
    }

    public static void main(String[] args) {
        //创建一个数组
        int[] arr = {1,2,3,4,5};

        //尝试通过一个越界索引来查找数组中的元素
        int num = getElement(arr, 5);
        //java.lang.ArrayIndexOutOfBoundsException: 大哥！索引越界了啊！
    }
}
~~~

### Throws——声明异常

+ 作用：运用于方法声明之上，用于表示当前方法不处理异常，而是提醒该方法的调用者来处理异常。

+ 格式：

  ~~~java
  修饰符 返回值类型 方法名(参数) throws 异常类名1, 异常类名2...{
      //EXEC statement
  }
  ~~~

**代码演示**

~~~java
import java.io.FileNotFoundException;

public class Test {
    //如果定义功能发生编译时异常需要报告给调用者，
    //可以通过在方法上使用throws关键字进行声明
    public static void read(String path) throws FileNotFoundException {
        if (!"b.txt".equals(path)) {
            throw new FileNotFoundException("文件路径错误！");
        }
    }
    
    public static void main(String[] args) throws FileNotFoundException {
        read("a.txt");
    }
}
~~~

> `throws`用于进行异常类的声明，若该方法可能有多种异常情况，那么在`throws`后面可以写多个异常类，用逗号隔开。

### try...catch——捕获异常

+ 作用：对异常有针对性的语句进行捕获，可以对出现的异常进行指定方式的处理。

+ 格式：

  ~~~java
  try {
      可能会出现异常的代码;
  } catch (异常类型 e){
      处理异常的代码;
  }
  ~~~

**代码演示**

~~~java
import java.io.FileNotFoundException;

public class Test {
    //定义读取文档方法，里面有抛出异常的代码
    public static void read(String path) throws FileNotFoundException{
        //如果文件路径不一致，则抛出异常
        if (!"a.txt".equals(path)) {
            throw new FileNotFoundException("文件路径不正确");
        }
    }

    public static void main(String[] args) {
        String path = "a.txt";
        try {
            read(path);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
~~~

### finally——代码块

+ 作用：

  1. 有一些特定的代码无论异常是否发生，都需要执行。
  2. 另外，因为异常会引发程序跳转，导致有些语句执行不到。而`finally`就是解决这个问题的，在`finally`代码块中存放的代码都是一定会被执行的。
  3. 当我们在`try`语句块中打开了一些物理资源（磁盘文件/数据库连接等），我们都得在使用完之后，最终关闭打开的资源。所以一般我们都会在`finally`代码块里面添加关闭资源的语句。

+ 格式：

  ~~~java
  import java.io.FileNotFoundException;
  
  public class Test {
      //如果定义功能发生编译时异常需要报告给调用者，
      //可以通过在方法上使用throws关键字进行声明
      public static void read(String path) throws FileNotFoundException {
          if (!"b.txt".equals(path)) {
              throw new FileNotFoundException("文件路径错误！");
          }
      }
  
      public static void main(String[] args) {
          try {
              read("a.txt");
          } catch (FileNotFoundException e) {
              e.printStackTrace();
          } finally {
              System.out.println("不管程序怎样，这里都会被执行");
          }
      }
  }
  ~~~

> 当只有在`try`或者`catch`中调用退出`JVM`的相关方法，此时`finally`才不会被执行，否则`finally`永远都会执行。

## 自定义异常类

我们说了`Java`中不同的异常类，分别表示着某一种具体的异常情况，那么在开发中总是有些异常情况是`SUN`公司没有定义好的。此时就需要我们根据自己业务的异常情况来定义异常类了。

**异常类如何定义：**

1. 自定义一个编译器异常：自定义类并继承于`java.lang.Exception`。
2. 自定义一个运行时期的异常类：自定义类并继承于`java.lang.RuntimeException`。

**代码演示**

要求：我们模拟注册操作，如果用户名已存在，则抛出异常并提示。

~~~java
//定义登录异常类RegisterException (继承Exception为编译时异常)
class RegisterException extends Exception {
    //空参构造
    public RegisterException() {

    }

    //通过调用super调用父类构造器，传入表示异常的提示
    public RegisterException(String message) {
        super(message);
    }
}

//模拟登录操作，使用数组模拟数据库中存储的数据，并提供当前注册账号是否存在的方法用于判断
public class Test {
    //模拟数据库中已存在的账号
    private static String[] users = {"Jason", "Johnson", "Jones"};

    //定义判断账号是否存在的方法
    private static void checkUser(String name) throws RegisterException {
        for (String user: users) {
            //用户名存在，就抛出登陆异常
            if(user.equals(name)) {
                throw new RegisterException("亲" + name + "已经被注册了");
            }
        }
    }

    public static void main(String[] args) {
        try {
            //调用方法
            checkUser("Jason");
        } catch (RegisterException e) {//捕获自定义的异常
            e.printStackTrace();
        }
    }
}
~~~

## 注意事项

1. 多个异常使用捕获又该如何处理呢？
   + 多个异常分别处理

   + 多个异常一次捕获，一次处理

   + 多个异常一次捕获，多次处理

     一般我们是使用【一次捕获，多次处理】的方法，格式如下：

     ~~~java
     try {
          编写可能会出现异常的代码;
     } catch(异常类型A e) {
         处理异常的代码;
     } catch(异常类型B e) {
         处理异常的代码;
     }
     ~~~

     > 1. 这种异常处理方式，要求多个catch中的异常不能相同。
     > 2. 并且若catch中的多个异常之间有子父类异常的关系，那么子类异常要求在上面的catch处理，父类异常在下面的catch处理。

2. 运行时异常被抛出可以不处理（即不捕获，也不声明抛出）。
3. 如果`finally`有`return`语句，则会永远返回`finally`中的结果，要避免该情况。
4. 如果父类抛出了多个异常，子类重写父类方法时。抛出和父类相同的异常 或 父类异常的子类 或 不抛出异常(子类不能抛出比父类多的异常)。
5. 父类方法没有抛出异常，子类重写父类该方法时也不可能抛出异常。此时子类产生异常，只能捕获处理，不能声明抛出。

